from __future__ import annotations


class BaseLLM:
    def generate(self, prompt: str, **kwargs) -> str:
        raise NotImplementedError


class StubLLM(BaseLLM):
    def generate(self, prompt: str, **kwargs) -> str:
        instruction = prompt.split("Instruction:")[-1].strip() if "Instruction:" in prompt else prompt
        return f"""# Generated by StubLLM
# Task: {instruction[:60]}

def placeholder():
    \"\"\"TODO: implement {instruction[:40]}\"\"\"
    pass
"""
